updated CI for ssdaemon

diff --git a/.github/workflows/compile_test.yml b/.github/workflows/compile_test.yml
--- a/.github/workflows/compile_test.yml
+++ b/.github/workflows/compile_test.yml
@@ -20,22 +20,8 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libvlc-dev
       
-    # - name: Install GLIBC 2.31 for compability
-    #   run: |
-    #     sudo apt-get update
-    #     sudo apt-get install -y build-essential wget
-    #     wget http://ftp.gnu.org/gnu/libc/glibc-2.31.tar.gz
-    #     tar -xzf glibc-2.31.tar.gz
-    #     cd glibc-2.31
-    #     mkdir build && cd build
-    #     ../configure --prefix=/opt/glibc-2.31
-    #     make -j$(nproc)
-    #     sudo make install
-    #     echo "Using older GLIBC..."
-    #     export LD_LIBRARY_PATH=/opt/glibc-2.31/lib:$LD_LIBRARY_PATH
-
     - name: Compile
-      run: g++ main.cpp -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lvlc -static-libstdc++ -o ASAPCabinetFE
+      run: g++ src/main.cpp -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lvlc -static-libstdc++ -o ASAPCabinetFE
 
     - name: Check Compilation
       run: |
@@ -45,12 +31,6 @@ jobs:
           echo "Compilation failed!"
           exit 1
         fi
-
-    # - name: Upload ASAPCabinetFE Artifact
-    #   uses: actions/upload-artifact@v4
-    #   with:
-    #     name: ASAPCabinetFE
-    #     path: ASAPCabinetFE
 
   compile_config:
     runs-on: ubuntu-latest
@@ -66,22 +46,8 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y build-essential git libsdl2-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev libfreetype6-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
 
-    # - name: Install GLIBC 2.31 for compability
-    #   run: |
-    #     sudo apt-get update
-    #     sudo apt-get install -y build-essential wget
-    #     wget http://ftp.gnu.org/gnu/libc/glibc-2.31.tar.gz
-    #     tar -xzf glibc-2.31.tar.gz
-    #     cd glibc-2.31
-    #     mkdir build && cd build
-    #     ../configure --prefix=/opt/glibc-2.31
-    #     make -j$(nproc)
-    #     sudo make install
-    #     echo "Using older GLIBC..."
-    #     export LD_LIBRARY_PATH=/opt/glibc-2.31/lib:$LD_LIBRARY_PATH
-
     - name: Compile
-      run: g++ config.cpp -std=c++17 imgui/*.cpp imgui/backends/imgui_impl_sdl2.cpp imgui/backends/imgui_impl_opengl3.cpp -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -Iimgui -Iimgui/backends -lSDL2 -lGL -static-libstdc++ -o config
+      run: g++ src/config.cpp -std=c++17 imgui/*.cpp imgui/backends/imgui_impl_sdl2.cpp imgui/backends/imgui_impl_opengl3.cpp -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -Iimgui -Iimgui/backends -lSDL2 -lGL -static-libstdc++ -o config
 
     - name: Check Compilation
       run: |
@@ -91,9 +57,29 @@ jobs:
           echo "Compilation failed!"
           exit 1
         fi
-        
-    # - name: Upload config Artifact
-    #   uses: actions/upload-artifact@v4
-    #   with:
-    #     name: config
-    #     path: config
+
+  compile_screenshotdaemon:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+      with:
+        submodules: true
+
+    - name: Install System Dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y build-essential libsdl2-dev libsdl2-ttf-dev
+
+    - name: Compile
+      run: g++ src/screenshot_daemon.cpp -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -lSDL2 -lSDL2_ttf -pthread -o screenshot_daemon
+
+    - name: Check Compilation
+      run: |
+        if [ -f screenshot_daemon ]; then
+          echo "Compilation successful!"
+        else
+          echo "Compilation failed!"
+          exit 1
+        fi
