added config to CI

diff --git a/.github/workflows/compile_test.yml b/.github/workflows/compile_test.yml
--- a/.github/workflows/compile_test.yml
+++ b/.github/workflows/compile_test.yml
@@ -8,7 +8,7 @@ on:
     branches: [ "main" ]
 
 jobs:
-  compile:
+  compile_app:
     runs-on: ubuntu-latest
 
     steps:
@@ -27,6 +27,31 @@ jobs:
     - name: Check Compilation
       run: |
         if [ -f ASAPCabinetFE ]; then
+          echo "Compilation successful!"
+        else
+          echo "Compilation failed!"
+          exit 1
+        fi
+
+  compile_config:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y build-essential libsdl2-dev libsdl2-ttf-dev
+        
+    - name: Compile
+      run: g++ config.cpp -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -lSDL2 -lSDL2_ttf -o config
+
+
+    - name: Check Compilation
+      run: |
+        if [ -f config ]; then
           echo "Compilation successful!"
         else
           echo "Compilation failed!"
